Added DMM Trailer
jvlflame/Javinizer pull request #90
Opened 2020-09-19 03:03 UTC by seeyabye

This PR adds a DMM trailer for DmmJA.

2020-09-19 03:20 UTC, seeyabye commented
I realized that there's different trailer qualities. I should check this accordingly.

2020-09-19 03:45 UTC, jvlflame commented
Thanks for the PR @seeyabye!

For reference on the R18 scraper, I just have it default to the highest quality version rather than output all found qualities.
Have you tested the function on both the English/Japanese dmm sites, or only the Japanese one?

2020-09-19 05:43 UTC, seeyabye commented
I have revised the way of getting the trailer URL. It should now get the highest quality by default as well.

As for the tests, I've only done it on the Japanese DMM site. I'm not too sure how to test it on the English DMM site as I constantly get redirected back to the Japanese version.

2020-09-20 08:05 UTC, jvlflame requested changes

2020-09-20 08:05 UTC, jvlflame commented on src/Javinizer/Private/Scraper.Dmm.ps1
> +            $trailerUrl = ((Invoke-WebRequest -Uri $trailerPageUrl -WebSession $session -Verbose:$false).Content | Select-String -Pattern '\\/\\/cc3001\.dmm\.co\.jp\\/litevideo\\/freepv[^"]+').Matche
You can remove the `-WebSession` parameter as $session isn't being assigned in the function.
Seems to be working properly for `dmmja`, but not for `dmm`. 

$iFrameUrl is correct, but $trailerPageUrl seems to be being set with an invalid URL, (i.e. for IPX-219: https://www.dmm.co.jp/en/service/digitalapi/-/html5_player/=/cid=ipx219/mtype=AhRVShI_/service=mono/floor=dvd/mode=/ )

Let's add a string replacement to $trailerPageUrl of `-Replace '/en', ''` and it should output the correct URL.

2020-09-20 23:26 UTC, seeyabye commented
I've incorporated the fix. @jvlflame do you mind checking if it works for `dmm`? Thanks!

2020-09-21 03:26 UTC, jvlflame commented
After further testing, turns out we do need to incorporate the websession in in $trailerPageUrl.
I made a few small changes to resolve that, so we should be good to merge.

2020-09-21 03:27 UTC, merged